version: '3.9'

services:
  db:
    image: postgres:15
    container_name: my_postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB:-mydatabase}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-admin@admin.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "8080:80"
    depends_on:
      - db

  backend:
    build:
      context: .
      dockerfile: docker/Dockerfile.backend
    container_name: backend
    depends_on:
      - db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432

      MODEL_TYPE: ${MODEL_TYPE:-lstm}
      EPOCHS: ${EPOCHS:-10}
      BATCH_SIZE: ${BATCH_SIZE:-128}
      LR: ${LR:-0.001}
      TRAIN_MODEL: ${TRAIN_MODEL:-False}
      SEQ_LEN: ${SEQ_LEN:-30}
      MODEL_PATH: ${MODEL_PATH:-./result/model/lstm_model.pth}
    ports:
      - "8000:8000"

  ui:
    build:
      context: .
      dockerfile: docker/Dockerfile.ui
    container_name: ui
    depends_on:
      - backend
    ports:
      - "5173:5173"

volumes:
  db_data:
